language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

services:
  - elasticsearch
  - mysql

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.1.0.deb && sudo service elasticsearch restart
  - pip install --upgrade setuptools==49.6.0
  - pip install --upgrade pip==18.1
  - pip install flake8
  - pip install coveralls
  - pip install -r "requirements.txt"
  - pip install -r "requirements_tests.txt"

script:
  - flake8 .
  - cd tests
  - coverage run --source=sirmordred run_tests.py

after_success:
  - coveralls
