language: python

python:
  - "3.4"

sudo: false

services:
  - elasticsearch
  - mysql

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.1.0.deb && sudo service elasticsearch restart
  - pip install httpretty==0.8.6
  - pip install -r "requirements.txt"
  - pip install flake8
  - pip install coveralls

script:
  - flake8 .
  - cd tests
  - coverage run --source=sirmordred run_tests.py

after_success:
  - coveralls
